/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aivlis
 */
public class NewJFrame extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TosSeca = new javax.swing.JCheckBox();
        TosFlemas = new javax.swing.JCheckBox();
        Fiebre38 = new javax.swing.JCheckBox();
        Fiebre38Mas = new javax.swing.JCheckBox();
        Fiebre40 = new javax.swing.JCheckBox();
        EscurrimientoNasal = new javax.swing.JCheckBox();
        Ronquera = new javax.swing.JCheckBox();
        SonidoRespirar = new javax.swing.JCheckBox();
        OpresionPecho = new javax.swing.JCheckBox();
        SilvidoRespiratorio = new javax.swing.JCheckBox();
        CuerpoCortado = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 3, 18)); // NOI18N
        jLabel1.setText("Seleccione los sintomas.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 40, 220, 23);

        TosSeca.setText("Tos seca");
        TosSeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TosSecaActionPerformed(evt);
            }
        });
        getContentPane().add(TosSeca);
        TosSeca.setBounds(70, 90, 80, 23);

        TosFlemas.setText("Tos con flemas");
        getContentPane().add(TosFlemas);
        TosFlemas.setBounds(70, 140, 110, 23);

        Fiebre38.setText("Temperatura mayor o igual a 38°");
        getContentPane().add(Fiebre38);
        Fiebre38.setBounds(70, 190, 220, 23);

        Fiebre38Mas.setText("Temperatura de 38 ° a 39°");
        Fiebre38Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fiebre38MasActionPerformed(evt);
            }
        });
        getContentPane().add(Fiebre38Mas);
        Fiebre38Mas.setBounds(70, 240, 180, 23);

        Fiebre40.setText("Temperatura mayor o igual a 40°");
        getContentPane().add(Fiebre40);
        Fiebre40.setBounds(70, 290, 230, 23);

        EscurrimientoNasal.setText("Escurrimiento Nasal");
        getContentPane().add(EscurrimientoNasal);
        EscurrimientoNasal.setBounds(70, 350, 130, 23);

        Ronquera.setText("Ronquera");
        getContentPane().add(Ronquera);
        Ronquera.setBounds(350, 90, 90, 23);

        SonidoRespirar.setText("Sonido al respirar");
        getContentPane().add(SonidoRespirar);
        SonidoRespirar.setBounds(350, 140, 120, 23);

        OpresionPecho.setText("Opresion en el pecho");
        getContentPane().add(OpresionPecho);
        OpresionPecho.setBounds(350, 190, 130, 23);

        SilvidoRespiratorio.setText("Silvido Respiratorio");
        getContentPane().add(SilvidoRespiratorio);
        SilvidoRespiratorio.setBounds(350, 240, 130, 23);

        CuerpoCortado.setText("Cuerpo Cortado");
        getContentPane().add(CuerpoCortado);
        CuerpoCortado.setBounds(350, 290, 120, 23);

        jButton1.setFont(new java.awt.Font("Californian FB", 3, 14)); // NOI18N
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 380, 69, 27);

        jLabel2.setText("Gripa Comun:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 470, 80, 14);

        jLabel3.setText("Laringitis:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 510, 70, 14);

        jLabel4.setText("Asma: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 470, 40, 20);

        jLabel5.setText("Bronquitis: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 510, 70, 14);

        jLabel6.setText("Pulmonia:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 470, 60, 14);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 460, 80, 30);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 500, 80, 30);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(330, 460, 80, 30);

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(330, 500, 80, 30);

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(480, 460, 80, 30);

        jLabel7.setFont(new java.awt.Font("Simplified Arabic", 3, 14)); // NOI18N
        jLabel7.setText("Probabilidad de que presenta la enfermedad.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 430, 280, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TosSecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TosSecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TosSecaActionPerformed

    private void Fiebre38MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fiebre38MasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fiebre38MasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double pgc; double pl; double pa; double pb; double pp;
        Red enfermedades = new Red(); // crea una variable de la clase Red
        //inicializa en False todos los sintomas.
        String TS="False"; String TF="False"; String CC="False"; String EN ="False";
        String OP="False"; String R="False"; String SilR="False"; String SonR="False"; 
        String F38="False"; String FM38="False"; String F40="False";
        //dependiendo si se selecciona el sintoma se cambian a True.
        if(TosSeca.isSelected()){TS="True";}
        if(TosFlemas.isSelected()){TF="True";}
        if(CuerpoCortado.isSelected()){CC="True";}
        if(EscurrimientoNasal.isSelected()){EN="True";}
        if(OpresionPecho.isSelected()){OP="True";}
        if(Ronquera.isSelected()){R="True";}
        if(SilvidoRespiratorio.isSelected()){SilR="True";}
        if(SonidoRespirar.isSelected()){SonR="True";}
        if(Fiebre38.isSelected()){F38="True";}
        if(Fiebre40.isSelected()){F40="True";}
        if(Fiebre38Mas.isSelected()){FM38="True";}
        String[] sintomasGC = new String[3]; //crea un arreglo de string
        sintomasGC[0]=TS; sintomasGC[1]=EN; sintomasGC[2]=F38;
        double[] gripaComun;
        gripaComun = enfermedades.CalcularGripaComun(sintomasGC); // se obtienen las probabilidades de que tenga gripa comun
        pgc=gripaComun[0]*100;
        String probabilidades;
        probabilidades=pgc+"%";
        jTextField1.setText(probabilidades); //imprime la probabilidad de que tenga gripa comun.
        double[] laringitis;
        laringitis = enfermedades.CalcularLaringitis(R, gripaComun); // se obtiene la probabilidad de que tenga laringitis
        String[] sintomasA = new String[3];
        pl=laringitis[0]*100;
        probabilidades=pl+"%";
        jTextField2.setText(probabilidades); //imprime la probabilidad de que tenga laringitis.
        sintomasA[0]=TS; sintomasA[1]=TF; sintomasA[2]=SilR;
        double[] asma;
        asma = enfermedades.CalcularAsma(sintomasA); // se obtiene la probabilidad de que tenga asma.
        pa=asma[0]*100;
        probabilidades=pa+"%";
        jTextField3.setText(probabilidades); //imprime la probabilidad de que tenga asma.
        String[] sintomasB = new String[4];
        sintomasB[0]=TF; sintomasB[1]=OP; sintomasB[2]=FM38; sintomasB[3]=CC;
        double[] bronquitis;
        bronquitis = enfermedades.CalcularBronquitis(sintomasB); // se obtiene la probabilidad de que tenga bronquitis.
        pb=bronquitis[0]*100;
         probabilidades=pb+"%";
        jTextField4.setText(probabilidades); //imprime la probabilidad de que tenga bronquitis.
        String[] sintomasP = new String[3];
        sintomasP[0]=F40; sintomasP[1]=CC; sintomasP[2]=TF;
        double[] pulmonia;
        pulmonia = enfermedades.CalcularPulmonia(sintomasP); // se obtiene la probabilidad de que tenga pulmonia.
        pp=pulmonia[0]*100;
        probabilidades=pp+"%";
        jTextField5.setText(probabilidades); //imprime la probabilidad de que tenga pulmonia.
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CuerpoCortado;
    private javax.swing.JCheckBox EscurrimientoNasal;
    private javax.swing.JCheckBox Fiebre38;
    private javax.swing.JCheckBox Fiebre38Mas;
    private javax.swing.JCheckBox Fiebre40;
    private javax.swing.JCheckBox OpresionPecho;
    private javax.swing.JCheckBox Ronquera;
    private javax.swing.JCheckBox SilvidoRespiratorio;
    private javax.swing.JCheckBox SonidoRespirar;
    private javax.swing.JCheckBox TosFlemas;
    private javax.swing.JCheckBox TosSeca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
